version: '3.1'
services:
  db:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: root
    ports:
    - "3306:5432"
    volumes:
      - devdojo_data:/var/lib/postgresql

volumes:
  devdojo_data: